### ISSUE TITLE
Parameter DPI funktioniert nicht richtig

### ISSUE THREAD

**Issue by romefi** [opengisch/qgis_server_render_geojson#2]
Die Eingabe der DPI "dpi=96" scheint grundsätzlich zu funktionieren, am Bild ändert sich was mit unterschiedlichen DPI, aber die DPI im ausgegebenen PNG ist immer 100, egal was in der URL mitgegeben wird.

**Comment by m-kuhn** [comment]
Upstream fix also pending https://github.com/qgis/QGIS/pull/36302
