### ISSUE TITLE
Python exception when running on desktop

### ISSUE THREAD

**Issue by Gustry** [opengisch/qgis_server_render_geojson#3]
Because the plugin is published on plugins.qgis.org, I tried to install it because QGIS Desktop notified me it was a new plugin and it looked interesting ;-)

I didn't know it was a server only plugin.
It's possible to add this dummy class to avoid the Python exception:
https://github.com/3liz/qgis-wfsOutputExtension/blob/master/wfsOutputExtension/__init__.py#L7

My 2 cents ;-)

**Comment by m-kuhn** [comment]
Thanks for the input. Ideally a `desktop=false` would be added to metadata.txt to hide it from there?

**Comment by Gustry** [comment]
Yes, it would be better indeed.
