### ISSUE TITLE
metadata.txt to mention QGIS Server

### ISSUE THREAD

**Issue by sfkeller** [opengisch/qgis_server_render_geojson#4]
Interesting plugin. I was close to install it on QGIS Desktop before I realized that this is a QGIS _Server_ plugin... So I'd propose to change the description in metadata.txt a bit (besides some small typos).

Change description (#L4 https://github.com/opengisch/qgis_server_render_geojson/blob/master/qgis_server_render_geojson/metadata.txt#L4 from) from

> This plugins renders geojson files. The file to render is specified as a GET parameter and downloaded or located locally on the server. The qml style to use can be specified through a second parameter.

to 

> This QGIS Server plugin renders GeoJSON files. The file to render is specified as a GET parameter and downloaded or located locally on the server. The QML style to use can be specified through a another parameter.

**Comment by m-kuhn** [comment]
Thanks.
For reference, see also this issue https://github.com/opengisch/qgis_server_render_geojson/issues/3
